#!/usr/bin/env python3
"""Expand all 10 city guide pages with rich investment content."""

import os
import re

BASE = "/Users/atlas/Desktop/terrasolana/cities"

# Content blocks per city — prose, no bullet points
# Structure: intro (keep existing) → neighbourhoods → rental_demand → risks → property_types → cta
CONTENT = {
    "valencia": {
        "search_param": "valencia",
        "browse_label": "Browse Valencia listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Ruzafa is where Valencia's investment activity is densest, and with good reason. This former working-class barrio immediately south of the city centre has spent the last decade attracting independent restaurants, design studios and a rotating cast of Erasmus graduates who refuse to leave. Demand for 2-bedroom apartments here is structural rather than cyclical, and yields consistently land in the 5.5–6.5% range on well-maintained stock. The floor prices have moved, but not so far that the numbers stop working.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Cabanyal, Valencia's historic fishing quarter on the seafront, represents the city's best remaining value-growth story. Long neglected and partially blighted by an old demolition threat that was eventually dropped, it has spent the past five years gentrifying rapidly without yet fully repricing. Properties here can still be acquired at €1,600–2,000/m² while comparable coastal stock in Málaga or Alicante trades at twice that. The short-term rental market is active, and long-let demand from young professionals priced out of Ruzafa keeps void periods short. Yields of 6.5–8% are achievable on the right purchase.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">L'Eixample, Valencia's Haussmann-inspired grid between the old town and the Gran Vía, offers a different risk profile — lower yield (4–5%) but higher liquidity and a tenant base of established professionals and corporate relocators. It is the defensive choice: slower appreciation upside, but deep rental demand and an easy resale market if circumstances change.</p>""",
        "demand_title": "Why renters choose Valencia",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Valencia's rental market is unusually diversified, which is what makes it resilient. The Universitat de València and the Universitat Politècnica together enrol around 90,000 students, generating a dense layer of demand for studio and 2-bedroom apartments within cycling distance of both campuses. That demand is non-negotiable: student enrolment is not correlated with economic cycles, and Valencia's universities draw heavily from Latin America as well as across Spain.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Layered on top of the student base is a fast-growing cohort of digital nomads and remote-working Europeans. Valencia has deliberately cultivated this segment — the Tech Valencia hub, co-working infrastructure, and relatively low cost of living compared to Lisbon or Barcelona have made the city a standard reference on every "best cities for remote workers" index. These tenants are typically mid-to-high income, stay 6–18 months, and pay reliably. They cluster in Ruzafa, El Carmen, and the seafront barrios.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Short-term tourism adds a third income layer. Valencia receives over 3 million overnight visitors annually, and the Americas Cup legacy infrastructure has meaningfully upgraded the city's international profile. Landlords with tourist licences in the right zones report occupancy rates above 80% across ten months of the year.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The primary regulatory risk in Valencia is the tourist licence environment. The Valencian Community has progressively tightened its VUT (Vivienda de Uso Turístico) framework, and several inner-city zones — particularly around El Carmen and parts of Ruzafa — have had new licence issuance frozen while the city develops its revised short-term rental plan. Buyers should verify whether any property they are considering has an existing, transferable licence rather than assuming one can be obtained post-purchase.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">On the long-let side, Spain's national rental legislation (Ley de Arrendamientos Urbanos) is broadly tenant-friendly. Minimum lease terms of five years for individual tenants mean that pricing flexibility is limited once a contract is in place. This is not a dealbreaker — it is simply a reality that long-let investors need to price correctly from day one rather than relying on annual increases to compensate for a below-market initial rent.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Competition from other investors has intensified significantly since 2021. Prime Ruzafa and coastal Cabanyal stock regularly receives multiple offers. Buyers approaching Valencia as a passive, set-and-forget market may find that the best opportunities require faster decision-making than they are accustomed to in other markets.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The 2-bedroom apartment — between 60m² and 85m² — is Valencia's highest-demand rental unit. It serves student flat-shares, couples, and young professionals equally well, keeps void periods to a minimum, and offers sufficient rental income to make the numbers work across most entry price points below €250,000. Prioritise properties with natural light, outdoor space (even a small balcony), and good connectivity to university campuses or the city centre by bike or metro.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Studio and 1-bedroom apartments in El Cabanyal and around the Benimaclet student zone represent the higher-yield, higher-turnover end of the market. Entry prices can be found below €120,000 for habitable stock, and rental demand from students and young professionals is consistently strong. The trade-off is higher management intensity: these units turn over more frequently and require more active landlord involvement or a good local property manager.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For buyers seeking lower management overhead, larger apartments in L'Eixample targeting corporate long-let tenants offer a more hands-off profile. These let quickly to professionals and companies, hold value well, and rarely require significant intervention. The yield floor is lower, but the net return after costs tends to compare favourably once vacancy and management expense is properly modelled.</p>"""
    },

    "madrid": {
        "search_param": "madrid",
        "browse_label": "Browse Madrid listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Carabanchel is the barrio that Madrid's serious yield investors discovered first and that mainstream commentary is now beginning to catch up with. Located in the south of the city, directly accessible by metro to the business districts of Nuevos Ministerios and Cuatro Torres, it combines prices still below €2,200/m² with rental demand driven by young professionals who can no longer afford Arganzuela or Malasaña. Gross yields of 6.5–8% are achievable; net yields after costs typically land in the 4.5–5.5% range. The gentrification runway remains long.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Tetuán, in the north of the city along the Paseo de la Castellana, offers a different profile. Once dismissed as a transit neighbourhood, it has been comprehensively transformed by the arrival of the BBVA campus, improved metro connectivity and a wave of restaurant and retail openings along its main commercial streets. The tenant base is now heavily professional — young corporate workers priced out of Chamberí — and average rents have risen sharply while entry prices still sit 25–30% below comparable Salamanca stock. Yields in the 5.5–7% range are the current norm.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Vallecas remains Madrid's highest-yield district, with gross returns regularly reaching 8–11% on the right purchases. The tenant base is diverse and demand is consistent, but this is a market for investors who understand the area and are prepared to manage it actively. Vacancy risk is lower than its reputation suggests, but the quality of purchase matters more here than in more forgiving markets: the gap between a good property and a difficult one is wider than elsewhere.</p>""",
        "demand_title": "Why renters choose Madrid",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Madrid is Spain's primary corporate relocation destination, and that structural fact underpins long-let rental demand in a way that no other Spanish city can replicate. The concentration of multinational European headquarters, Spanish banking sector offices, government institutions, and legal and consulting firms in the capital creates a continuous stream of high-income professional tenants arriving in 1–3 year rotations, seeking quality long-let apartments near metro lines. These tenants pay reliably, treat properties well, and rarely negotiate on rent.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Madrid's university population — close to 300,000 students across Complutense, Autónoma, Carlos III and a dozen smaller institutions — creates a parallel rental market for lower-priced stock near campuses. The Moncloa-Aravaca and Ciudad Universitaria zones, as well as the areas around the Leganés and Getafe campuses in the southern metro area, have structurally low vacancy rates driven by student demand alone.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The city's emergence as a European tech hub — with Google, Microsoft, Amazon and a dense cluster of Spanish unicorns concentrated in the northern corridors — has added a third tenant profile: young international tech workers with relatively high salaries who choose Madrid over London or Amsterdam for quality-of-life reasons. They are willing to pay premium rents for well-located, well-designed apartments and are increasingly resistant to the poor-quality stock that dominated the market a decade ago.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Madrid's single biggest investor risk is political. The city's rental market sits in the middle of a sustained national debate about housing affordability, and successive governments have introduced and modified rental control mechanisms under the Ley de Vivienda. The current framework includes reference rent indices in so-called tensioned zones, and while enforcement has been inconsistent, the direction of regulatory travel is clearly toward greater constraint on landlord pricing power. Buyers should model their returns conservatively, assuming limited rent growth in the short term.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Madrid's tourist licence (VUT) framework is active, but the city has not implemented the freezes seen in some coastal markets. The registration process is clear and licences are transferable with the property. Buyers intending to operate short-term rentals should factor licence acquisition costs and the management intensity of STR operations into their return assumptions from the outset.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The high entry price point is the operational constraint that most limits yield. In prime inner-city barrios — Salamanca, Chamberí, Retiro — prices have moved to levels where gross yields rarely exceed 3.5–4%. Investors targeting meaningful yield need to look to the second and third rings. The trade-off is management complexity: these areas require greater landlord involvement or reliable local management to perform at their potential.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The most consistently performing asset class in Madrid is the renovated 2-bedroom apartment between 55m² and 80m² in the mid-ring barrios — Carabanchel, Tetuán, Usera, Vallecas — priced in the €140,000–€220,000 range. At these entry points, gross yields of 6.5–8% are achievable with well-managed long-let strategy, and the depth of tenant demand means that void periods, when they occur, are measured in days rather than months.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Studio apartments within walking distance of metro stations are Madrid's most liquid rental asset. They let immediately, attract a wide range of tenant profiles — students, young professionals, short-rotation corporate workers — and are the easiest to manage remotely. The yield on studios in accessible mid-ring locations typically runs 50–80 basis points above comparable 2-bedroom stock due to the price-per-m² differential at acquisition.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Larger apartments of 90m²+ in quality inner-ring barrios targeting corporate long-let represent the lowest management overhead available in Madrid. A single well-chosen corporate tenant on a three-year contract eliminates vacancy risk and management friction almost entirely. The yield is lower — typically 3.5–5% gross — but the total return including capital appreciation and negligible management cost compares well against more intensive strategies in outer districts.</p>"""
    },

    "malaga": {
        "search_param": "malaga",
        "browse_label": "Browse Málaga listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Palo and Pedregalejo, the string of former fishing villages running east along the coast from the city centre, represent Málaga's most interesting investment zone in 2026. They have benefited from the city's technology boom without yet being fully repriced into it — properties on and around the Playa del Palo can still be acquired at €2,200–2,800/m², offering meaningful upside against the trajectory of other Málaga coastal zones. Long-let demand is strong from the tech workforce: both neighbourhoods are a 20-minute metro ride from the Málaga Tech Hub corridor, close enough for professionals who want beach-adjacent living without Centro prices. Yields of 4.5–6% are achievable with long-let strategy.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Centro Histórico remains Málaga's highest-demand short-term rental zone, but it comes with the highest entry prices and a tightening licence environment. For buyers with an existing VUT licence in the portfolio, it is an excellent performing asset. For buyers attempting to acquire and licence new STR capacity in the historic centre, the regulatory outlook is uncertain enough to require careful diligence.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Cruz de Humilladero and Carranque offer the city's most favourable yield arithmetic for long-let investment. These are working residential barrios with prices well below the city median, consistent demand from the local workforce, and the kind of deep rental pool that keeps void periods short. Gross yields of 5.5–7.5% are achievable on well-located stock. Capital appreciation expectations are more modest than in coastal zones, but the income returns compare well against almost anywhere else in the Málaga metro area.</p>""",
        "demand_title": "Why renters choose Málaga",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Málaga's transformation from a transit city into a genuine tech destination has been the defining story of the Spanish property market over the past five years. The arrival of Google Cloud's Southern European campus, the Vodafone technology centre, and a dense cluster of startups and accelerators in the Málaga Tech Park has created a new professional tenant class that did not exist a decade ago — high-income, internationally mobile, and with strong preferences for quality residential property rather than the tourist-oriented stock that previously dominated the market.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">This structural shift in tenant demographics has coincided with a surge in remote-working professionals choosing Málaga as a base. The combination of reliable sun, good international flight connections (Málaga Airport is the fourth busiest in Spain), a growing English-language social scene and prices that remain below Lisbon or Valencia for comparable quality has made the city a top-three destination on virtually every digital nomad ranking published since 2021. These tenants represent long-stay, high-yield demand: they pay above-market rents for quality stock and typically stay 12–24 months.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Short-term tourism generates the third layer. The Costa del Sol's 14 million annual visitors and Málaga city's own cultural pull — the Picasso Museum, the contemporary art scene, the emerging restaurant culture — keep STR occupancy high in well-located properties. Properly managed tourist apartments in the right zones generate gross returns that long-let cannot match, though at the cost of greater management intensity and regulatory exposure.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Málaga's tourist licence framework is the market's primary operational risk. The Ayuntamiento has indicated intent to limit new VUT registrations in the historic centre and several coastal zones, following the pattern set by Barcelona and Palma. Buyers targeting short-term rental income should treat the existence of a current, transferable VUT licence as a significant premium factor — it may be worth paying above the average market price to acquire a licensed property rather than assuming new licences will be available post-purchase.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Price appreciation has been rapid enough in Málaga's most visible neighbourhoods that entry-level yield compression is a genuine concern. Centro properties that would have offered 5.5% gross in 2020 now yield 3.5–4%, and the capital required to enter the market has risen to a level where many individual investors find themselves squeezed. The best remaining yield opportunities require looking beyond the areas that feature most prominently in property marketing — which is precisely where Terrasolana's data layer adds most value.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Community fee structures (gastos de comunidad) in Málaga's older apartment buildings can be disproportionately high relative to property values. Budget for maintenance provisions and community fees carefully before finalising yield calculations — in older stock, these costs can erode net yield by 80–120 basis points compared to modern buildings.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The 1-bedroom or compact 2-bedroom apartment targeting the professional long-let market is the most reliable income-generating asset in Málaga right now. Units between 45m² and 70m² in good condition, with air conditioning and either a balcony or terrace, let within days to the city's growing tech and professional tenant base. Prioritise properties within 20 minutes of the Málaga Tech Hub by public transport and at entry prices below €220,000 to maintain viable yield arithmetic.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Properties with existing tourist licences in the Centro or Soho districts are genuinely scarce and command a premium that is, in most cases, justified by the income differential. A well-run STR in these zones can generate 40–60% more gross income than the same property on a long-let contract. The management intensity is higher, but for investors with good local operator relationships or plans to self-manage, the economics are compelling.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For investors seeking coastal exposure with a lower entry price than the prime beachfront commands, El Palo apartments in the €160,000–€220,000 range represent a high-conviction medium-term play: current income from long-let professional tenants, combined with appreciation upside as the tech corridor continues to extend east along the coast.</p>"""
    },

    "alicante": {
        "search_param": "alicante",
        "browse_label": "Browse Alicante listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Barrio — Alicante's compact, hilly old town below the Castillo de Santa Bárbara — is the city's most characterful investment zone and, for buyers willing to navigate its narrow streets and older building stock, one of its most rewarding. Properties here rent quickly to short-stay tourists and medium-term visitors attracted by the location; gross yields of 6–8% are achievable on well-presented apartments with tourist licences. Entry prices remain low relative to Málaga or Valencia equivalents, and the neighbourhood has genuine long-term appeal as a destination in its own right.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">San Antón, immediately east of the city centre and running up to the market area, offers a more residential profile with consistent long-let demand from local professionals and international expat residents. The housing stock here is a mix of 1970s–90s apartment buildings in decent condition and some newer development, and prices are reasonable by coastal standards — typically €1,500–2,000/m² for good stock. Long-let yields of 5–6.5% are the norm.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Playa de San Juan, Alicante's northern beach suburb, captures a different market entirely: medium-stay tourists and seasonal residents, primarily Northern European expats and retirees, who want sea views and beach access. Properties here are most valuable with tourist licences and tend to perform best as seasonal rentals — occupancy is concentrated in April through October, and net annual income can look attractive on paper but depends heavily on effective marketing and management during the season.</p>""",
        "demand_title": "Why renters choose Alicante",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Alicante's primary rental demand driver is one of Europe's largest and most established expat communities. Over 100,000 Northern Europeans — predominantly British, German, Scandinavian and Dutch — have settled in the Alicante province as permanent or semi-permanent residents, drawn by Spain's most reliable sunshine record (average 320 days per year), the lowest cost of living on the Mediterranean coast, and well-developed English-language infrastructure. These residents require long-let housing of a quality that the local market has historically underserved, creating a structural opportunity for landlords who understand their requirements.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The city's university — the Universidad de Alicante, with around 25,000 students — provides a consistent secondary demand layer for lower-priced studio and 2-bedroom stock in the campus-adjacent zones of San Vicente del Raspeig. Student demand here is year-round and price-insensitive to a degree: proximity to campus outweighs almost all other factors in tenant choice.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Short-stay tourism, particularly the growing segment of non-package travellers seeking self-catered apartment accommodation, drives STR demand in the historic centre and along the sea-facing boulevards. Alicante Airport handles over 14 million passengers annually and is one of the UK's most frequently served routes from multiple regional airports, ensuring a steady inbound flow across most of the calendar year.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The British buyer base that has historically been Alicante's most active international investor segment has faced post-Brexit complexity that reduced transaction volumes in the 2021–2023 period. The practical constraints — 90-day Schengen rules for non-residents, the end of free EU movement — remain in place, but British buyers have largely adapted: many are now acquiring as long-term visa holders or through Golden Visa routes, and the market has absorbed the regulatory change without structural disruption. Buyer confidence from the UK market has returned to pre-Brexit levels in 2025–2026.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Valencian Community's STR licensing framework applies to Alicante as to the rest of the region. Coastal zones with high tourist density are under the same scrutiny as other popular areas, and buyers should verify licence status carefully. The city itself has not yet implemented the moratoriums seen in some other markets, but the regulatory direction is toward tighter control rather than liberalisation.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Seasonal income concentration is the operational risk that most catches investors off-guard. Properties dependent on tourist income can generate 70–80% of their annual revenue between May and September, leaving five to seven months with modest bookings. Buyers should stress-test their yield models at 60% annual occupancy rather than peak-season rates, and consider whether a hybrid long-let / seasonal approach makes more sense for their risk tolerance.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Apartments with terraces or sea-view balconies are Alicante's premium rental asset — they command meaningful rent premiums in both the long-let and STR markets, and they are what the expat and tourist tenant bases specifically search for. A 2-bedroom apartment with outdoor space in a maintained building within 500 metres of the beach or the city centre will let quickly, hold value through market cycles, and outperform comparable interior stock on total return.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The old town (El Barrio) offers the most interesting value proposition for investors comfortable with older building stock: relatively low acquisition prices, strong STR demand, genuine character that cannot be replicated in modern suburban developments, and material upside if — as seems likely — Alicante continues to attract increasing international attention as an alternative to the more expensive Costa del Sol.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For long-let income with minimal management overhead, quality 2-bedroom apartments in the San Antón and Carolinas Bajas barrios targeting professional expat tenants represent the steadiest income profile in the market. Entry prices in the €110,000–€170,000 range, rents of €700–950/month, and tenants who typically stay two to four years add up to a simple, low-friction investment proposition.</p>"""
    },

    "almeria": {
        "search_param": "almeria",
        "browse_label": "Browse Almería listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The city centre (Centro) is Almería's most active investment zone, and it justifies the attention. A compact, well-maintained historic core with a striking Moorish fortress (the Alcazaba), good restaurants and a functioning commercial street life, it attracts a mix of long-let demand from local professionals and civil servants, short-stay cultural tourists, and the academic population associated with the Universidad de Almería. Properties in the centre can still be acquired at prices that would be unthinkable in any comparable Mediterranean city — €800–1,400/m² for habitable stock in many cases — which is precisely why gross yields of 7–10% remain available to diligent buyers.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">La Chanca, the historically Arab-influenced fishing quarter immediately below the Alcazaba, is Almería's most overtly regenerating neighbourhood. It remains rough around the edges, and buyers should approach it with realistic expectations about the pace of change, but it offers the city's lowest entry prices alongside genuine character and a location that will eventually attract the gentrification premium its geography deserves. This is a ten-year play, not a three-year one — but the entry prices make the patience affordable.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Costacabana, the beach suburb running south-east along the coast from the city, captures the leisure and short-term tourism market. Beachfront and near-beach apartments here offer access to Almería's most consistent STR demand — the city's beaches are genuinely excellent and significantly less crowded than anything on the Costa del Sol or Costa Blanca — and entry prices for seafront stock that would be three times the price in Alicante or Málaga remain available.</p>""",
        "demand_title": "Why renters choose Almería",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Almería's rental demand base is more concentrated than that of other Spanish cities, which is both a risk and a feature of the market. The dominant driver is the agricultural and agri-food sector: Almería province supplies roughly a third of Europe's salad vegetables, and the workforce associated with that industry — at every level from field workers to logistics managers to food-tech professionals at the Cajamar cooperative network — creates substantial residential demand that is essentially non-seasonal and tied to a genuinely critical economic activity.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Universidad de Almería, with around 12,000 students, adds a layer of young professional and academic tenant demand to the centre and the campus-adjacent districts. This is a smaller student population than Valencia or Granada, but it is sufficient to keep well-located student-oriented stock occupied through the academic year. The university has been actively growing its international student intake, which bodes well for long-term rental demand from this segment.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Film and screen tourism generates a niche but interesting short-term demand stream. The Tabernas Desert — Europe's only true desert, 35 kilometres from the city — hosted the filming of hundreds of spaghetti westerns and remains an active location for productions. Cultural tourists visiting the preserved western sets at Oasys MiniHollywood and Fort Bravo contribute to the city's growing short-stay visitor numbers, alongside the entirely mainstream appeal of Almería's uncrowded beaches.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Almería's most significant investment risk is liquidity. This is a genuine secondary market — not illiquid in absolute terms, but significantly less traded than Valencia, Madrid or Málaga. Buyers should assume that in a distressed scenario they would need six to twelve months to find a buyer at a fair price, and price their expected return accordingly. The entry prices reflect this premium-for-illiquidity, but the premium exists for a reason.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Capital appreciation has historically been modest in Almería compared to the coastal headline markets, though this is partly a function of starting from very low prices. The city has not experienced the explosive appreciation of Málaga or Valencia over 2021–2025, and buyers targeting primarily capital growth should look elsewhere. For buyers focused on income return, the low entry prices and high gross yields offer strong current income in a way that faster-appreciating cities cannot match.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Tenant quality management requires more attention in Almería's lower-price-point market than in more professionally oriented cities. The rental market is functioning, but the diligence required at tenant selection to avoid problematic occupancies is real. Building a local management relationship — whether a property manager or a reliable local agent — is not optional here in the way it might be considered optional in Madrid or Valencia.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Large apartments (80–110m²) in the Centro at below-€100,000 entry prices represent Almería's most distinctive investment proposition. These properties would trade at three to four times the price in any other Mediterranean city, and the rental demand from professional and civil servant tenants at €600–800/month produces gross yields that make any serious yield investor recalibrate their assumptions about what is achievable in Spain. The properties require renovation investment in many cases, but the mathematics work even with significant refurbishment cost factored in.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Studio and 1-bedroom apartments near the university campus targeting the student market offer the highest yield-per-euro of entry investment in Almería's portfolio, typically in the €55,000–€80,000 acquisition range with gross yields running above 10% in some cases. These require more active management than the professional long-let segment, but the income return is difficult to match anywhere in Spain at comparable entry prices.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Beachfront apartments in Costacabana for STR operation represent Almería's most speculative but potentially most rewarding property type. Entry prices for sea-view stock in the €90,000–€130,000 range, combined with summer STR occupancy that easily supports €2,000–3,000/month gross in peak season, make for compelling summer income numbers. The shoulder season occupancy rate is the key underwriting variable — investors should model conservatively and verify actual local occupancy data before buying.</p>"""
    },

    "granada": {
        "search_param": "granada",
        "browse_label": "Browse Granada listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Realejo — the former Jewish quarter on the hill below the Alhambra — is Granada's most investable neighbourhood for buyers navigating the city's complex tourist licence environment. It sits just outside the strictest historic-centre STR restrictions, has strong short-stay demand from visitors to the Alhambra, and a growing population of artists, academics and young professionals who have been priced out of the Albaicín. Properties here — typically 1–3 bedroom apartments in historic buildings, often with small patios or terraces — can generate gross yields of 6–8% and tend to appreciate alongside Granada's rising cultural profile.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Zaidín, in the southern part of the city, is Granada's best pure long-let investment zone. It is a large, functional residential barrio with excellent transport links, consistent demand from the university student population (the Universidad de Granada's science faculties are nearby), and prices that remain well below the historic centre. Gross yields of 7–8.5% are achievable on well-located apartments at entry prices in the €100,000–€160,000 range. It is not glamorous, but it is reliable and well-understood by the local market.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Albaicín itself — Granada's Moorish hilltop quarter and UNESCO World Heritage Site — is the city's most visually spectacular but most regulation-exposed investment zone. Tourist licences are extremely difficult to obtain and in many parts of the neighbourhood effectively impossible for new acquisitions. Properties with existing, valid licences command significant premiums and represent a scarce, income-generating asset. Buying unlicensed in the Albaicín with the intention of operating STR is not advisable without specialist legal advice.</p>""",
        "demand_title": "Why renters choose Granada",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Granada's rental market is disproportionately driven by its university, which is one of Spain's largest and oldest. The Universidad de Granada enrols over 60,000 students — a remarkable figure for a city of 240,000 — and is one of Spain's most popular Erasmus receiving institutions, attracting thousands of international students each year who add to the year-round demand for rental accommodation. The student influence on the rental market is pervasive: it keeps rents competitive across a wide range of property types, maintains low vacancy even in periods of wider economic stress, and creates a tenant base that is almost permanently renewing.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Alhambra tourism drives the short-stay market to levels that few Spanish cities outside Barcelona and Madrid can match. The Alhambra is the most visited monument in Spain — over 2.5 million tickets are sold annually, with access strictly limited by timed-entry controls that have the effect of extending visitor stays in the city. Tourists who have come to see the Alhambra tend to spend two to three nights in Granada rather than one, and a significant proportion prefer apartment accommodation to hotels. This is a structural demand driver that has no obvious downside over any planning horizon.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">A growing creative and digital professional community has added a third tenant layer in recent years. Granada's combination of quality university infrastructure, a functioning cultural scene, low cost of living and reasonable international connectivity has made it an increasingly popular base for location-flexible professionals — the kind of tenants who stay 12–18 months, pay reliably, and tend to upgrade the properties they occupy.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Tourist licence restrictions in Granada are the most complex of any city in Terrasolana's coverage. The historic zones — particularly the Albaicín and the immediate environs of the Alhambra — are subject to both municipal planning restrictions (PGOU) and Junta de Andalucía regulations that, in combination, make new VFT (Vivienda de Fines Turísticos) registration in most of the highest-demand areas effectively impossible. Buyers who acquire in these zones expecting to convert to STR will be disappointed. The value of existing licensed properties reflects this scarcity.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The depth of student rental demand, while an overall positive, creates a specific management challenge: the academic calendar creates predictable void periods in July and August when students depart, and property managers need to plan specifically for this turnover. Buildings dominated by student tenancies can require significant cleaning and maintenance between tenancies; budgeting properly for this is essential to accurate net yield calculation.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Granada's topography — much of the best residential stock sits on hillsides — creates practical maintenance challenges that flat-city investors underestimate. Buildings on steep streets have no vehicle access for deliveries or contractor visits; renovation costs tend to run higher than in comparable properties in accessible locations; and older buildings on the Albaicín and Realejo hillsides can have drainage and structural issues that require expert local building survey before purchase.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Multi-room apartments configured for shared student occupancy — typically 3–4 bedrooms with individual lettings contracts — are Granada's highest-yield asset class. A 4-bedroom apartment in Zaidín, acquired for €150,000–€180,000, can generate €1,400–1,800/month in aggregate room rents against long-let market rents of €900–1,100 for the equivalent whole-apartment contract. The management overhead is significantly higher, but specialist student property managers in Granada are well-established and charge reasonable fees.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Historic properties with existing tourist licences in El Realejo or the outer Albaicín are Granada's most sought-after investment asset. Supply is genuinely constrained — these licences are not being replaced when properties change hands without them — and the income differential between licensed and unlicensed properties in the same street is substantial. A 2-bedroom licensed apartment near the Alhambra generates materially more annual income than a 3-bedroom unlicensed property a block away. The premium is typically justified.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For investors who want reliable income without the complexity of the student or STR markets, compact 2-bedroom apartments in the Genil, Chana and Campus zones targeting professional and academic long-let tenants offer a clean, well-understood proposition. Entry prices in the €110,000–€160,000 range, consistent demand from university staff and professional tenants, and gross yields of 5.5–7% make this the lowest-friction investment approach available in the Granada market.</p>"""
    },

    "sevilla": {
        "search_param": "sevilla",
        "browse_label": "Browse Sevilla listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Triana, Sevilla's famed neighbourhood on the west bank of the Guadalquivir, is the city's single best investment barrio. It combines a strong and culturally coherent identity — flamenco, ceramics, independent restaurants, a local market — with an intensely active rental market that serves both short-stay tourists and long-let professional tenants. The latter have been arriving in increasing numbers as Triana's reputation has crossed from purely touristic into genuinely desirable residential. Gross yields of 5.5–7% are achievable on apartments in good condition; licensed STR properties in the right streets can do better. Entry prices (€2,000–2,800/m²) are still materially below comparable areas in Madrid or Barcelona.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Macarena, the barrio stretching north of the historic centre along the old city walls, is Sevilla's most interesting emerging investment zone. It is authentic in a way that the tourist-oriented Casco Histórico cannot be, with a local commercial life and a diverse population that has increasingly attracted young professionals priced out of the centre. The university faculties along the Macarena corridor generate consistent student demand, and the arrival of new coffee shops, independent retail and cultural venues is tracking the pre-gentrification pattern seen in Barcelona's Gràcia or Madrid's Tetuán five to eight years earlier. Entry prices of €1,600–2,200/m² make the yield arithmetic work.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Los Remedios, the residential barrio on the south bank adjacent to Triana, is Sevilla's most established professional long-let zone — the equivalent of Madrid's Chamberí, albeit at a fraction of the price. It lacks the character of Triana or the upside story of Macarena, but it offers deep, reliable demand from Sevilla's business and legal professional class and properties in good condition that do not require the intensive management that tourist-licence zones demand. Yields of 4.5–5.5% gross with low vacancy are the consistent norm.</p>""",
        "demand_title": "Why renters choose Sevilla",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Sevilla's rental demand is anchored by two structural pillars that are essentially immune to economic cycles. The first is tourism: Sevilla is Spain's third most visited city, and the combination of the Alcázar, the Cathedral, Semana Santa and the Feria de Abril generates year-round short-stay demand that is broader and more evenly distributed across the calendar than most tourist cities manage. Peak demand runs from March through October, with meaningful off-season activity from European cultural travellers filling the quieter months.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The second pillar is one of Spain's largest university systems. The Universidad de Sevilla, together with the Universidad Pablo de Olavide and several professional schools, enrolls over 70,000 students. The student population is particularly concentrated in the barrios surrounding the historic campus — Macarena, Triana, San Bernardo — and generates dense, price-insensitive rental demand that has supported the long-let market through every economic cycle of the past thirty years.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">A third and growing segment is the corporate and Erasmus professional tenant. Sevilla's aerospace cluster (Airbus, Alestis, the Centro Avanzado de Tecnologías Aeroespaciales) employs thousands of engineers and professionals who require quality mid-market rental accommodation. This segment is expanding as the aerospace industry in Sevilla grows, and it represents the kind of creditworthy, long-stay tenant that makes income forecasting straightforward.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Sevilla's tourist licence framework is the most actively restrictive of any city in Andalucía. The Ayuntamiento de Sevilla, under sustained political pressure to address housing affordability concerns driven by STR-induced rent inflation, has implemented significant restrictions on new VFT registrations in the Casco Histórico and several immediately adjacent zones — including substantial parts of Triana. The practical effect is that unlicensed properties in these areas cannot be converted to short-term rental use, and the value differential between licenced and unlicensed stock has widened considerably. Buyers must verify licence status with a specialist solicitor before any purchase intended for STR use.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Sevilla's summer heat is a real factor in both tenant experience and property management. The city regularly records Spain's highest summer temperatures — 40°C+ is routine in July and August — and properties without effective air conditioning are genuinely difficult to let at any price point during the peak summer months. Budget for quality climate control as a non-negotiable operating cost, and factor cooling costs into net yield calculations for the five-month summer period.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The IBI (property tax) in Sevilla is above the national average for comparable cities, and community fees in older Casco buildings can be significant. Run detailed net yield calculations accounting for local tax rates, community fees and maintenance provisions before committing — gross yield figures for Sevilla can overstate net returns more than in lower-cost-base markets if ownership costs are not properly modelled.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Properties with existing, transferable VFT licences in Triana and the central barrios are Sevilla's scarcest and most reliably income-producing investment asset. Supply is limited and shrinking as older licensed properties change hands without licence transfer in some cases. A licensed 2-bedroom apartment in a well-located Triana street, producing €2,500–3,500/month gross in the tourist season and €1,100–1,400/month as a long-let fallback, represents a defensible income asset even at the premiums these properties now command.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">2 and 3-bedroom apartments in Macarena targeting the student and young professional long-let market represent the city's best value play for yield-focused buyers. Entry prices in the €150,000–€210,000 range, rents of €900–1,300/month for whole-apartment lets (or significantly more on room-by-room student configurations), and genuine upside from the neighbourhood's continued trajectory make this the highest-conviction medium-term opportunity in the Sevilla market.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Buyers seeking low management overhead and steady professional tenants should look at Los Remedios for 2-bedroom apartments in good condition targeting the corporate and aerospace sector professional. These properties require minimal management, attract creditworthy long-term tenants, and represent the simplest income proposition available in the Sevilla market — albeit at the lower end of the yield range.</p>"""
    },

    "murcia": {
        "search_param": "murcia",
        "browse_label": "Browse Murcia listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The city centre (Centro) is Murcia's most investment-active zone and the one where the yield arithmetic works most consistently. A dense, walkable urban core built around the baroque cathedral and a network of commercial streets, it generates demand from student tenants, civil servants, retail and hospitality workers, and the academic staff of two universities. Properties here are typically 1970s–80s apartment buildings in variable condition; quality refurbishments can achieve rents that compress gross yields to 5–6%, but the right purchase at the right price can reach 7–8%. Entry prices of €1,000–1,600/m² make Murcia's centre one of Spain's most accessible city-centre investment markets.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Ranero and the university campus zone represent Murcia's best pure student investment corridor. The Universidad de Murcia's main campus is located here, and the demand density for studio and 2-bedroom apartments within a short walk of the faculty buildings is essentially constant throughout the academic year. Entry prices are typically below the city average, and the rental income from room-by-room student lets can push gross yields well above the long-let norm for comparable properties.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">La Flota and Infante Juan Manuel, residential barrios to the east of the centre, offer the city's most consistent professional long-let market. These areas house much of Murcia's working professional population — government employees, healthcare workers, teachers — and properties in good condition with car parking let quickly and hold their tenancies for extended periods. Gross yields of 5.5–7% are achievable at current entry prices.</p>""",
        "demand_title": "Why renters choose Murcia",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Murcia's most defining rental demand characteristic is the sheer scale of its student population relative to its total size. With the Universidad de Murcia (approximately 35,000 students) and the Universidad Católica de Murcia — UCAM (approximately 30,000 students) operating within the metropolitan area, the city has a combined higher education enrolment of around 65,000 students. In a city of 450,000 people, this represents an extraordinary proportion of the rental market and explains why well-located student-oriented stock in Murcia has historically produced some of the highest yields in Spain's regional markets.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The agricultural and agri-food sector provides a secondary but substantial demand layer. Murcia's huerta — its famous fertile plain — supports one of Spain's most productive agricultural regions, and the food processing, logistics and export infrastructure built around it employs a large professional and technical workforce that requires long-let residential accommodation. This is permanent, non-seasonal demand tied to a genuinely essential economic sector rather than a cyclical or fashion-driven market.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Costa Cálida — Murcia's coastline, including the resorts of Mazarrón, Águilas and the Mar Menor — generates coastal tourism demand that feeds back into city property as a base for visitors and seasonal residents. While most direct tourist rental activity occurs in the coastal municipalities rather than the city itself, the infrastructure and workforce associated with coastal tourism maintains a consistent presence in Murcia city's rental market.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Murcia's most significant investment limitation is the relatively underdeveloped international investor market. Unlike Málaga, Valencia or Alicante, Murcia does not feature prominently on the radar of the European international buyer, which means that the market is predominantly domestic and that liquidity — while adequate — is shallower than in better-known cities. Buyers should assume a slightly extended disposal timeline in the event of a forced sale and price their expected return accordingly.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Capital appreciation in Murcia has been significantly more modest than in coastal or headline markets over the past five years. Buyers whose return model relies on material price growth will need to look elsewhere. The Murcia investment case is an income story — high yields from deeply structural demand — rather than an appreciation story, and investors who understand this from the outset tend to find the market rewarding.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The student-let market, while profitable, requires active property management. High tenant turnover at the end of each academic year creates predictable maintenance cycles and void periods in July and August that must be budgeted for. Buildings with a high proportion of student tenancies also tend to require more frequent maintenance intervention than professional long-let stock. Factor these costs carefully before finalising net yield projections.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Multi-room apartments configured for student occupancy are Murcia's highest-yield residential asset, and the depth of demand from both universities means that well-located examples in the campus zone are among the most reliably occupied rental properties anywhere in Spain. A 4–5 bedroom apartment near the Universidad de Murcia campus, acquired for €130,000–€170,000 and rented room-by-room at €250–350/room, can generate gross yields comfortably above 10%. The management requirement is real, but the economics are compelling.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">2-bedroom apartments in the city centre and adjacent barrios targeting professional long-let tenants represent Murcia's most straightforward income investment. At entry prices of €80,000–€130,000 and rental income of €550–750/month, gross yields of 7–8% are achievable with relatively low management overhead. These properties tend to be in older buildings and may require refurbishment investment, but the yield arithmetic absorbs renovation cost well at Murcia's current price levels.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">UCAM-adjacent apartments near the Guadalupe campus in the eastern suburbs of Murcia represent an underserved niche: the private university attracts a higher proportion of international students and has been growing enrolment aggressively, but the surrounding rental market is less developed than the Universidad de Murcia zone. Entry prices here can be lower still, and investors willing to develop local management relationships in a less competitive submarket may find the best yield-per-euro available in the wider Murcia metro area.</p>"""
    },

    "palma": {
        "search_param": "palma",
        "browse_label": "Browse Palma listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Santa Catalina has been Palma's most celebrated residential transformation of the past decade. A former working-class market neighbourhood immediately west of the historic centre, it has evolved into the city's primary destination for young professionals, independent restaurants and wine bars, and the growing digital nomad population drawn to Mallorca's increasingly serious technology and creative sector. Long-let demand here is strong and sophisticated — tenants are typically European professionals with mid-to-high incomes — and gross yields of 4.5–6% are achievable on well-presented 1 and 2-bedroom apartments. Entry prices have moved significantly since 2019 but remain accessible relative to comparable neighbourhoods in Barcelona or Madrid.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Son Espanyolet, a quiet residential neighbourhood immediately north of Santa Catalina, is where Palma's long-let investment opportunity is clearest. Away from the tourist concentration of the Casco Antiguo and the weekend-restaurant foot traffic of Santa Catalina, it offers solid housing stock with good access to the centre, a stable professional tenant base, and prices that have not yet fully repriced to match its proximity to the city's most desirable areas. Gross yields of 4.5–5.5% are available; the profile is lower-management-intensity than anything tourist-adjacent.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Es Molinar, the coastal neighbourhood running east from the city towards the airport, occupies a different investment category: it is Palma's most accessible seafront area by price, combining beach access with a functioning residential community. Demand from the expat and seasonal resident market keeps vacancy low through a long season, and properties with outdoor space command strong premiums. This is a lifestyle market as much as a yield market — buyers are often motivated by personal use alongside investment — and the profile is accordingly different from the purely income-focused zones.</p>""",
        "demand_title": "Why renters choose Palma",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Palma benefits from year-round demand in a way that most Spanish resort cities do not. Mallorca has successfully diversified beyond the package holiday market into a destination for long-stay residents — particularly Northern Europeans seeking island living with direct flight connections to their home cities — and Palma city has built genuine urban infrastructure that supports permanent rather than purely seasonal occupation. The German expat community in particular is large, well-established and represents exactly the kind of reliable, long-tenure, creditworthy tenant base that generates strong net returns for landlords.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The summer tourism market remains the most intense in Spain — Mallorca receives over 12 million visitors annually and Palma is the gateway and primary accommodation hub for a significant proportion of them. Properties with valid tourist licences benefit from the highest seasonal STR demand of any city in Terrasolana's coverage, with peak-summer occupancy of 90%+ and nightly rates that drive annual gross income significantly above what long-let income can produce on equivalent stock.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">A growing technology and creative sector has added a year-round professional tenant base to Palma's previously seasonal economy. Startups, design firms, film production companies and technology businesses have established themselves in the city, attracted by the quality of life and good international connectivity. These tenants require quality urban apartments with fast internet and good public transport access — a profile that matches Santa Catalina and Son Espanyolet well.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Palma operates under the most restrictive tourist licence framework in Spain. The Balearic Government (Govern Balear) has been progressively reducing total licensed STR capacity since 2017 under the Ley Turística de las Illes Balears — the opposite direction from most mainland markets. In Palma city itself, apartment-based tourist licences (ETV — Estancias Turísticas en Viviendas) are effectively no longer being issued in most zones. The market for existing licensed properties is therefore a genuine scarcity market, and premiums of 30–60% over equivalent unlicensed stock are not uncommon.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Buyers intending to let on the open long-term rental market in Palma face a different but significant constraint: the Balearic Government has introduced rent reference indices and, in defined tensioned zones, caps on rent increases for new contracts. This framework is more actively enforced than mainland equivalents, and investors should model returns assuming limited rent growth for the foreseeable future. The base rent levels are, however, among the highest in Spain outside Barcelona and Madrid, which partially compensates for the restricted growth environment.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Entry prices in Palma are the highest in Terrasolana's Spanish coverage outside prime Madrid — comparable to Málaga's coastal zones and considerably above Sevilla, Granada or Murcia. This compresses yield arithmetic for buyers accustomed to the secondary city numbers. The investment case in Palma is most compelling for buyers who value capital preservation and appreciation alongside income, rather than those optimising purely for current yield.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Properties with existing, valid ETV tourist licences are Palma's most valuable and sought-after investment asset class by a significant margin. The combination of the licence moratorium, strong demand from operators and investors, and the premium STR income these licences unlock creates a market where licences themselves trade at material value. A 2-bedroom apartment in Casco Antiguo or Santa Catalina with a valid transferable ETV licence is worth materially more than an identical unlicensed property in the same building — in some cases 40–50% more — and the income differential over a five-year hold period more than justifies the premium.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For buyers focusing on long-let income without tourist licence exposure, quality 1 and 2-bedroom apartments in Santa Catalina and Son Espanyolet targeting the professional expat market represent the clearest proposition. Rents are strong — €1,000–1,600/month for a 2-bedroom apartment in good condition — and tenant quality from the European professional and creative community is high. The management overhead is low, tenancy lengths are typically one to three years, and the properties hold value well through any market condition.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Es Molinar coastal apartments, for buyers comfortable with a personal-use component alongside rental income, offer beach access at Palma prices rather than the premium coast commands elsewhere in Mallorca. These properties work best as seasonal lets supplemented by off-season professional tenancies — a hybrid model that, properly managed, generates stronger total income than either pure approach alone.</p>"""
    },

    "zaragoza": {
        "search_param": "zaragoza",
        "browse_label": "Browse Zaragoza listings →",
        "neighbourhoods_title": "The neighbourhoods that yield",
        "neighbourhoods": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">El Casco Histórico is Zaragoza's most active investment zone and has undergone a meaningful regeneration over the past decade that is far from complete. The area around La Seo cathedral, the Aljafería Palace and the Pilar square has attracted independent hospitality, cultural investment and a growing young professional population who are trading up from peripheral barrios. Properties here — typically flats in old buildings, often requiring modernisation — can be acquired at €900–1,500/m² and, properly refurbished, generate gross yields of 6.5–8.5% from a tenant base of young professionals and, in the most central streets, STR operations. The yield per refurbishment euro spent is among the highest in urban Spain.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Delicias, Zaragoza's densely populated western barrio, is the city's most straightforwardly productive long-let investment zone. One of the largest barrios in Spain by population (over 100,000 residents), it has the depth of rental market that allows investors to place properties quickly and replace tenants without extended voids. The tenant base is diverse — logistics and warehouse workers, immigrant families, students from the local vocational institutes — and the entry prices (€700–1,100/m²) produce some of the highest gross yields available in any Spanish city of this size. This is not a glamorous investment market, but it is a highly functional one.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">San José and Las Fuentes, residential barrios to the east of the centre adjacent to the Ebro river, offer a middle-ground profile: better housing stock than Delicias, good transport links to the university and the logistics corridor, and a stable professional tenant base. Entry prices of €900–1,300/m² support gross yields of 5.5–7%, and these areas have benefited from spillover regeneration from the Casco Histórico improvements.</p>""",
        "demand_title": "Why renters choose Zaragoza",
        "demand": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Zaragoza's most structurally important rental demand driver is its position as Spain's primary logistics hub. Situated precisely at the midpoint of the Madrid–Barcelona axis on the AP-2 motorway and the high-speed rail corridor, the city hosts Amazon's largest European fulfilment centre, Inditex's central distribution operation, a massive Mercedes-Benz automotive components plant, and hundreds of logistics, e-commerce and manufacturing businesses that chose the location specifically for its transport geography. This industrial base employs a large workforce — at all levels from warehouse operatives to logistics managers to international corporate professionals — that requires residential accommodation in a city without the natural tourism-driven demand that keeps southern cities well known to investors.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The Universidad de Zaragoza, one of Spain's oldest universities, enrolls around 30,000 students across campuses concentrated in and around the city centre. Student demand for rental housing is consistent and price-driven — the campus adjacency premium in Zaragoza is real, and well-located student-oriented stock near the main faculties in the Casco Histórico and San Francisco barrios maintains low void rates through the academic year.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The high-speed rail connection to Madrid (1h45m) and Barcelona (1h40m) has made Zaragoza a serious consideration for corporate commuters and professional workers who want affordable city living within striking distance of both capitals. This demographic is small but growing, and it represents exactly the kind of high-income, low-maintenance tenant that makes long-let income reliable.</p>""",
        "risks_title": "Risks and considerations",
        "risks": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Zaragoza's most significant investment constraint is its limited international profile. The city does not appear on the radar of European investors the way Málaga, Alicante or Valencia do, which means the buyer pool for resale is thinner and more domestic. This is a real liquidity consideration: investors who need or want the option of selling to an international buyer within a three to five-year horizon will find fewer options in Zaragoza than in coastal markets. The market is not illiquid, but it is a domestic Spanish market.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Capital appreciation has historically been below the national average in Zaragoza. The city's property market is driven by income fundamentals rather than scarcity or lifestyle premium, and it tends to move in line with broader Spanish economic conditions rather than outperforming them. Investors seeking the kind of price growth seen in Málaga or Valencia over 2021–2025 should set more modest expectations for Zaragoza. The income returns more than compensate, but only for investors whose primary objective is yield rather than appreciation.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Zaragoza's extreme climate — summer temperatures regularly exceeding 38°C and cold, windy winters — creates higher energy costs for tenants and maintenance requirements (air conditioning, heating systems) that are more significant than in milder Mediterranean cities. Budget adequately for climate control installation and maintenance as part of the refurbishment cost when acquiring older properties.</p>""",
        "property_title": "Best property types for investment",
        "property": """<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">The refurbished 2-bedroom apartment in the Casco Histórico is Zaragoza's most compelling investment proposition. At acquisition prices of €80,000–€130,000 for properties requiring refurbishment and €130,000–€170,000 for move-in condition stock, with post-refurbishment rents of €700–950/month achievable for well-presented apartments, the yield arithmetic is among the most favourable available in any Spanish provincial capital. The key is quality renovation: the gap between a well-refurbished property and a mediocre one in the Casco is visible in both rental premium and tenant quality, and the refurbishment investment is well spent.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">Larger apartments in Delicias configured for multi-room student or worker occupancy generate the highest raw yield in the Zaragoza market. Entry prices of €60,000–€100,000 for 3–4 bedroom apartments, let room-by-room at €250–320/room, produce gross yields that routinely exceed 10% for well-managed properties. The management overhead in this segment is the highest in the Zaragoza market, but local property management services are well-established and reasonably priced.</p>
<p style="color:var(--ink-2);line-height:1.8;margin-bottom:20px">For the lowest-friction income investment in Zaragoza, quality 1-bedroom apartments near the logistics corridor in the Actur and La Paz districts, targeting the professional workforce of the Amazon and Inditex operations, offer a simple and reliable proposition. These tenants are well-paid, stable, and prefer quality over price. Entry at €90,000–€130,000 with gross yields of 5.5–6.5% and tenancies that typically run two to four years makes this the most hands-off income available in the market.</p>"""
    },
}

# HTML template for the expanded content section
def build_content_block(city_key, data):
    return f"""  <p class="city-intro" id="city-intro-text"><!-- intro preserved --></p>

  <h2 style="font-family:var(--font-serif);font-size:26px;font-weight:800;margin:48px 0 20px;letter-spacing:-0.01em">{data['neighbourhoods_title']}</h2>
{data['neighbourhoods']}

  <h2 style="font-family:var(--font-serif);font-size:26px;font-weight:800;margin:48px 0 20px;letter-spacing:-0.01em">{data['demand_title']}</h2>
{data['demand']}

  <h2 style="font-family:var(--font-serif);font-size:26px;font-weight:800;margin:48px 0 20px;letter-spacing:-0.01em">{data['risks_title']}</h2>
{data['risks']}

  <h2 style="font-family:var(--font-serif);font-size:26px;font-weight:800;margin:48px 0 20px;letter-spacing:-0.01em">{data['property_title']}</h2>
{data['property']}

  <div class="city-cta">"""

def process_city(filename, city_key):
    filepath = os.path.join(BASE, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()

    data = CONTENT[city_key]

    # Find the intro paragraph content to preserve
    intro_match = re.search(r'<p class="city-intro">(.*?)</p>', html, re.DOTALL)
    if not intro_match:
        print(f"WARNING: No city-intro found in {filename}")
        return

    intro_text = intro_match.group(1).strip()

    # Build new content block (replace placeholder)
    new_block = build_content_block(city_key, data)
    new_block = new_block.replace('<!-- intro preserved -->', intro_text)

    # Replace from <p class="city-intro"> through just before <div class="city-cta">
    # Pattern: <p class="city-intro">...</p> ... old neighbourhood section ... <div class="city-cta">
    old_pattern = re.compile(
        r'<p class="city-intro">.*?</p>.*?<div class="city-cta">',
        re.DOTALL
    )

    if not old_pattern.search(html):
        print(f"WARNING: Pattern not found in {filename}")
        return

    new_html = old_pattern.sub(new_block, html, count=1)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_html)

    print(f"✓ {filename}")

# Process all 10 cities
city_files = {
    "valencia.html": "valencia",
    "madrid.html": "madrid",
    "malaga.html": "malaga",
    "alicante.html": "alicante",
    "almeria.html": "almeria",
    "granada.html": "granada",
    "sevilla.html": "sevilla",
    "murcia.html": "murcia",
    "palma.html": "palma",
    "zaragoza.html": "zaragoza",
}

for filename, city_key in city_files.items():
    process_city(filename, city_key)

print("\nAll done.")
